name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ls
    - name: make
      run: mkdir build
    - name: make
      run: ls
    - name: make check
      run: cd build
    - name: make distcheck
      run: cmake ./..
    - name: make distcheck
      run: make
    - name: make distcheck
      run: ./hello
