name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: cat /proc/version 
  # Label of the container job
  container-job:
    needs: login
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ros
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      rosx:
        # Docker Hub image
        image: jiayy2/ubuntu16.04-ros-kinetic-base:v2.1
    steps:
      - run: cat /home/a.sh
