name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker pull jiayy2/ubuntu16.04-ros-kinetic-base:v1
      - run: docker run -it --name="ros" jiayy2/ubuntu16.04-ros-kinetic-base:v2.1 bash -c "cd /home && ./b.sh"
