name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
             sudo apt install -y qemu-user-static binfmt-support
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
             docker pull jiayy2/nx_image:v1
             docker run -i -v /home/runner/work/buoyancy/buoyancy:/home/ros2/src jiayy2/nx_image:v1 bash -c \
             "cd /home/ros2 && source /opt/ros2/galactic/setup.bash \
              && colcon build --packages-select cpp_pubsub \
              && colcon test --event-handlers console_cohesion+ --return-code-on-test-failure --packages-select cpp_pubsub"
             # colcon build
