name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: (ls /home/runner/work/buoyancy/buoyancy)
      - name: Checkout
        uses: actions/checkout@v3
      - run: (ls /home/runner/work/buoyancy/buoyancy)
  container-job:
    needs: job1
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: jiayy2/ubuntu16.04-ros-kinetic-base:v1
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /home/runner/work/buoyancy/buoyancy:/home/jyy/catkin_ws/src
    steps:
      - run: (ls /home/jyy/catkin_ws/src)
      - run: (ls /home/jyy/catkin_ws/src)
