name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
defaults:
  run:
    shell: bash
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: ubuntu:latest
      #credentials:
       #  username: ${{ secrets.DOCKERHUB_USERNAME }}
        # password: ${{ secrets.DOCKERHUB_TOKEN }}
     # env:
     #  NODE_ENV: development
      ports:
        - 80
      volumes:
        - /usr/bin/docker:/usr/bin/docker
        - /home/runner/work/buoyancy/buoyancy:/home/runner/work/buoyancy/buoyancy
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
             sudo apt install -y qemu-user-static binfmt-support
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
             docker pull jiayy2/nx_image:v1
             docker run -it -v /home/runner/work/buoyancy/buoyancy:/home/runner/work/buoyancy/buoyancy jiayy2/nx_image:v1 bash
