name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
defaults:
  run:
    shell: bash
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
             sudo apt install -y qemu-user-static binfmt-support
  container-job:
    needs: job1
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: jiayy2/nx_image:v1
      credentials:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     # env:
     #  NODE_ENV: development
      ports:
        - 80
      volumes:
        - /home/runner/work/buoyancy/buoyancy:/home/ros2/src
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
             cd /home/ros2
             source /opt/ros2/galactic/setup.bash
             # colcon build
